### ISSUE TITLE
ttws fails on zero-byte files

### ISSUE THREAD

**Issue by tbeu** [simulatino/trimtrailingwhitespaces#19]
Empty files (e.g. [package.order](../../../thermocycle/Thermocycle-library/blob/master/ThermoCycle/Media/D4_CP/package.order)) raise an exception instead of simply being ignored.

```
trimming c:/Projects/Thermocycle-library_tbeu/ThermoCycle\Media\D4_CP\package.order

Oops! Failing to process file: c:/Projects/Thermocycle-library_tbeu/ThermoCycle\Media\D4_CP\package.order
Are you sure it is of pure ASCII or UTF8 encoding?
```

``` py
Traceback (most recent call last):
  File "c:\Python27\Scripts\ttws-script.py", line 9, in <module>
    load_entry_point('ttws==0.5.1-dev', 'console_scripts', 'ttws')()
  File "C:\Python27\lib\site-packages\ttws-0.5.1_dev-py2.7.egg\ttws\cli.py", line 77, in main
    trimWhitespace(filepath, eol)
  File "C:\Python27\lib\site-packages\ttws-0.5.1_dev-py2.7.egg\ttws\__init__.py", line 87, in trimWhitespace
    target.write("\n".join(lines) + "\n")
TypeError: must be unicode, not str
```

**Comment by dietmarw** [comment]
@beutlich Any news here?

**Comment by tbeu** [comment]
I simply forgot about it.
